### ISSUE TITLE
filters directory is not copied in https://github.com/spacefill/gibbon-mail/blob/master/docker-image/Dockerfile

### ISSUE THREAD

**Issue by Claire-Couppie** [spacefill/gibbon-mail#9]
This makes the folder not found and prevents the service to launch

```
review-app-env-4991-external-icobo1-gibbon-mail | error Command failed with exit code 1.
review-app-env-4991-external-icobo1-gibbon-mail | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
review-app-env-4991-external-icobo1-gibbon-mail | yarn run v1.22.4
review-app-env-4991-external-icobo1-gibbon-mail | $ node src/server.js
review-app-env-4991-external-icobo1-gibbon-mail | internal/modules/cjs/loader.js:968
review-app-env-4991-external-icobo1-gibbon-mail |   throw err;
review-app-env-4991-external-icobo1-gibbon-mail |   ^
review-app-env-4991-external-icobo1-gibbon-mail |
review-app-env-4991-external-icobo1-gibbon-mail | Error: Cannot find module '../filters'
review-app-env-4991-external-icobo1-gibbon-mail | Require stack:
review-app-env-4991-external-icobo1-gibbon-mail | - /src/src/app.js
review-app-env-4991-external-icobo1-gibbon-mail | - /src/src/server.js
review-app-env-4991-external-icobo1-gibbon-mail |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
review-app-env-4991-external-icobo1-gibbon-mail |     at Function.Module._load (internal/modules/cjs/loader.js:841:27)
review-app-env-4991-external-icobo1-gibbon-mail |     at Module.require (internal/modules/cjs/loader.js:1025:19)
review-app-env-4991-external-icobo1-gibbon-mail |     at require (internal/modules/cjs/helpers.js:72:18)
review-app-env-4991-external-icobo1-gibbon-mail |     at Object.<anonymous> (/src/src/app.js:23:17)
review-app-env-4991-external-icobo1-gibbon-mail |     at Module._compile (internal/modules/cjs/loader.js:1137:30)
review-app-env-4991-external-icobo1-gibbon-mail |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
review-app-env-4991-external-icobo1-gibbon-mail |     at Module.load (internal/modules/cjs/loader.js:985:32)
review-app-env-4991-external-icobo1-gibbon-mail |     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
review-app-env-4991-external-icobo1-gibbon-mail |     at Module.require (internal/modules/cjs/loader.js:1025:19) {
review-app-env-4991-external-icobo1-gibbon-mail |   code: 'MODULE_NOT_FOUND',
review-app-env-4991-external-icobo1-gibbon-mail |   requireStack: [ '/src/src/app.js', '/src/src/server.js' ]
review-app-env-4991-external-icobo1-gibbon-mail | }
review-app-env-4991-external-icobo1-gibbon-mail | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
review-app-env-4991-external-icobo1-gibbon-mail | error Command failed with exit code 1.
review-app-env-4991-external-icobo1-gibbon-mail | yarn run v1.22.4
review-app-env-4991-external-icobo1-gibbon-mail | $ node src/server.js
review-app-env-4991-external-icobo1-gibbon-mail | internal/modules/cjs/loader.js:968
review-app-env-4991-external-icobo1-gibbon-mail |   throw err;
review-app-env-4991-external-icobo1-gibbon-mail |   ^
review-app-env-4991-external-icobo1-gibbon-mail |
review-app-env-4991-external-icobo1-gibbon-mail | Error: Cannot find module '../filters'
review-app-env-4991-external-icobo1-gibbon-mail | Require stack:
review-app-env-4991-external-icobo1-gibbon-mail | - /src/src/app.js
review-app-env-4991-external-icobo1-gibbon-mail | - /src/src/server.js
review-app-env-4991-external-icobo1-gibbon-mail |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
review-app-env-4991-external-icobo1-gibbon-mail |     at Function.Module._load (internal/modules/cjs/loader.js:841:27)
review-app-env-4991-external-icobo1-gibbon-mail |     at Module.require (internal/modules/cjs/loader.js:1025:19)
review-app-env-4991-external-icobo1-gibbon-mail |     at require (internal/modules/cjs/helpers.js:72:18)
review-app-env-4991-external-icobo1-gibbon-mail |     at Object.<anonymous> (/src/src/app.js:23:17)
review-app-env-4991-external-icobo1-gibbon-mail |     at Module._compile (internal/modules/cjs/loader.js:1137:30)
review-app-env-4991-external-icobo1-gibbon-mail |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
review-app-env-4991-external-icobo1-gibbon-mail |     at Module.load (internal/modules/cjs/loader.js:985:32)
review-app-env-4991-external-icobo1-gibbon-mail |     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
review-app-env-4991-external-icobo1-gibbon-mail |     at Module.require (internal/modules/cjs/loader.js:1025:19) {
review-app-env-4991-external-icobo1-gibbon-mail |   code: 'MODULE_NOT_FOUND',
review-app-env-4991-external-icobo1-gibbon-mail |   requireStack: [ '/src/src/app.js', '/src/src/server.js' ]
review-app-env-4991-external-icobo1-gibbon-mail | }
review-app-env-4991-external-icobo1-gibbon-mail | error Command failed with exit code 1.
```

**Comment by stephane-klein** [comment]
@Claire-Couppie bug fixed, Docker image pushed
